server:
  port: 8001
spring:
  application:
    name: VIDEO
  zipkin:
    base-url: http://103.97.179.91:9411/
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    nacos:
      server-addr: 101.43.187.7:8848

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.43.187.7:3306/drift?characterEncoding=UTF-8&useSSL=false
    username: root
    password: Szx123456
mybatis-plus:
  global-config:
    db-config:
      table-prefix: flow_
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
