server:
  port: 9999
spring:
  application:
    name: GATEWAY
  zipkin:
    base-url: http://38.34.245.48:9411/
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    nacos:
      discovery:
        server-addr: 103.97.179.91
        ip: 38.34.245.48
    gateway:
      routes:
        - id: video_router
          uri: lb://VIDEO
          predicates:
            - Path=/video/**

        - id: auth_router
          uri: lb://AUTH
          predicates:
            - Path=/auth/**

        - id: userInfo_router
          uri: lb://USER-INFO
          predicates:
            - Path=/userInfo/**

        - id: comment_router
          uri: lb://VIDEO-COMMENT
          predicates:
            - Path=/comment/**

        - id: tag_router
          uri: lb://TAG
          predicates:
            - Path=/tag/**

        - id: follow_router
          uri: lb://FOLLOW
          predicates:
            - Path=/follow/**

        - id: message_router
          uri: lb://MESSAGE
          predicates:
            - Path=/message/**

        - id: chat_router
          uri: lb://CHAT-NETTY
          predicates:
            - Path=/ws/**

        - id: search_router
          uri: lb://SEARCH
          predicates:
            - Path=/search/**