server:
  port: 7777

spring:
  application:
    name: AUTH
  zipkin:
    base-url: http://38.34.245.48:9411/
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    nacos:
      discovery:
        server-addr: 103.97.179.91
        ip: 38.34.245.48

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://158.51.124.2:8066/test?characterEncoding=UTF-8&useSSL=false
    username: root
    password: Szx123456
  redis:
    password: Szx123456
    sentinel:
      master: mymaster
      nodes: 38.34.245.48:16379, 66.187.4.234:16379, 158.51.124.2:16379

mybatis-plus:
  global-config:
    db-config:
      table-prefix: flow_
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
