server:
  port: 8007
spring:
  application:
    name: TAG
  zipkin:
    base-url: http://38.34.245.48:9411/
  cloud:
    nacos:
      discovery:
        server-addr: 103.97.179.91
        ip: 38.34.245.48