server:
  port: 8004
netty:
  port: 8005
  application:
    name: CHAT-NETTY
spring:
  application:
    name: CHAT
  cloud:
    nacos:
      discovery:
        server-addr: 103.97.179.91
        ip: 38.34.245.48
rocketmq:
  name-server: 38.34.245.48:9876
  producer:
    group: chat-productor